// Code generated by MockGen. DO NOT EDIT.
// Source: ../sso/internal/services/authservice/auth.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/AlexBlackNn/authloyalty/sso/internal/domain"
	broker "github.com/AlexBlackNn/authloyalty/sso/pkg/broker"
	gomock "github.com/golang/mock/gomock"
	proto "google.golang.org/protobuf/proto"
)

// MockgetResponseChanSender is a mock of getResponseChanSender interface.
type MockgetResponseChanSender struct {
	ctrl     *gomock.Controller
	recorder *MockgetResponseChanSenderMockRecorder
}

// MockgetResponseChanSenderMockRecorder is the mock recorder for MockgetResponseChanSender.
type MockgetResponseChanSenderMockRecorder struct {
	mock *MockgetResponseChanSender
}

// NewMockgetResponseChanSender creates a new mock instance.
func NewMockgetResponseChanSender(ctrl *gomock.Controller) *MockgetResponseChanSender {
	mock := &MockgetResponseChanSender{ctrl: ctrl}
	mock.recorder = &MockgetResponseChanSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgetResponseChanSender) EXPECT() *MockgetResponseChanSenderMockRecorder {
	return m.recorder
}

// GetResponseChan mocks base method.
func (m *MockgetResponseChanSender) GetResponseChan() chan *broker.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResponseChan")
	ret0, _ := ret[0].(chan *broker.Response)
	return ret0
}

// GetResponseChan indicates an expected call of GetResponseChan.
func (mr *MockgetResponseChanSenderMockRecorder) GetResponseChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponseChan", reflect.TypeOf((*MockgetResponseChanSender)(nil).GetResponseChan))
}

// Send mocks base method.
func (m *MockgetResponseChanSender) Send(ctx context.Context, msg proto.Message, topic, key string) (context.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, msg, topic, key)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockgetResponseChanSenderMockRecorder) Send(ctx, msg, topic, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockgetResponseChanSender)(nil).Send), ctx, msg, topic, key)
}

// MockuserStorage is a mock of userStorage interface.
type MockuserStorage struct {
	ctrl     *gomock.Controller
	recorder *MockuserStorageMockRecorder
}

// MockuserStorageMockRecorder is the mock recorder for MockuserStorage.
type MockuserStorageMockRecorder struct {
	mock *MockuserStorage
}

// NewMockuserStorage creates a new mock instance.
func NewMockuserStorage(ctrl *gomock.Controller) *MockuserStorage {
	mock := &MockuserStorage{ctrl: ctrl}
	mock.recorder = &MockuserStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserStorage) EXPECT() *MockuserStorageMockRecorder {
	return m.recorder
}

// GetUser mocks base method.
func (m *MockuserStorage) GetUser(ctx context.Context, uuid string) (context.Context, domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, uuid)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(domain.User)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUser indicates an expected call of GetUser.
func (mr *MockuserStorageMockRecorder) GetUser(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockuserStorage)(nil).GetUser), ctx, uuid)
}

// GetUserByEmail mocks base method.
func (m *MockuserStorage) GetUserByEmail(ctx context.Context, email string) (context.Context, domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(domain.User)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockuserStorageMockRecorder) GetUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockuserStorage)(nil).GetUserByEmail), ctx, email)
}

// HealthCheck mocks base method.
func (m *MockuserStorage) HealthCheck(ctx context.Context) (context.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockuserStorageMockRecorder) HealthCheck(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockuserStorage)(nil).HealthCheck), ctx)
}

// SaveUser mocks base method.
func (m *MockuserStorage) SaveUser(ctx context.Context, email string, passHash []byte) (context.Context, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", ctx, email, passHash)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockuserStorageMockRecorder) SaveUser(ctx, email, passHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockuserStorage)(nil).SaveUser), ctx, email, passHash)
}

// UpdateSendStatus mocks base method.
func (m *MockuserStorage) UpdateSendStatus(ctx context.Context, uuid, status string) (context.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSendStatus", ctx, uuid, status)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSendStatus indicates an expected call of UpdateSendStatus.
func (mr *MockuserStorageMockRecorder) UpdateSendStatus(ctx, uuid, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSendStatus", reflect.TypeOf((*MockuserStorage)(nil).UpdateSendStatus), ctx, uuid, status)
}

// MocktokenStorage is a mock of tokenStorage interface.
type MocktokenStorage struct {
	ctrl     *gomock.Controller
	recorder *MocktokenStorageMockRecorder
}

// MocktokenStorageMockRecorder is the mock recorder for MocktokenStorage.
type MocktokenStorageMockRecorder struct {
	mock *MocktokenStorage
}

// NewMocktokenStorage creates a new mock instance.
func NewMocktokenStorage(ctrl *gomock.Controller) *MocktokenStorage {
	mock := &MocktokenStorage{ctrl: ctrl}
	mock.recorder = &MocktokenStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenStorage) EXPECT() *MocktokenStorageMockRecorder {
	return m.recorder
}

// CheckTokenExists mocks base method.
func (m *MocktokenStorage) CheckTokenExists(ctx context.Context, token string) (context.Context, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTokenExists", ctx, token)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckTokenExists indicates an expected call of CheckTokenExists.
func (mr *MocktokenStorageMockRecorder) CheckTokenExists(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTokenExists", reflect.TypeOf((*MocktokenStorage)(nil).CheckTokenExists), ctx, token)
}

// GetToken mocks base method.
func (m *MocktokenStorage) GetToken(ctx context.Context, token string) (context.Context, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToken", ctx, token)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetToken indicates an expected call of GetToken.
func (mr *MocktokenStorageMockRecorder) GetToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MocktokenStorage)(nil).GetToken), ctx, token)
}

// SaveToken mocks base method.
func (m *MocktokenStorage) SaveToken(ctx context.Context, token string, ttl time.Duration) (context.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToken", ctx, token, ttl)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveToken indicates an expected call of SaveToken.
func (mr *MocktokenStorageMockRecorder) SaveToken(ctx, token, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToken", reflect.TypeOf((*MocktokenStorage)(nil).SaveToken), ctx, token, ttl)
}
