// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4eaa2564DecodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV1(in *jlexer.Lexer, out *Response) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = string(in.String())
		case "error":
			out.Error = string(in.String())
		case "access_token":
			out.AccessToken = string(in.String())
		case "refresh_token":
			out.RefreshToken = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4eaa2564EncodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV1(out *jwriter.Writer, in Response) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	if in.Error != "" {
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		out.String(string(in.Error))
	}
	if in.AccessToken != "" {
		const prefix string = ",\"access_token\":"
		out.RawString(prefix)
		out.String(string(in.AccessToken))
	}
	if in.RefreshToken != "" {
		const prefix string = ",\"refresh_token\":"
		out.RawString(prefix)
		out.String(string(in.RefreshToken))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Response) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4eaa2564EncodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Response) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4eaa2564EncodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Response) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4eaa2564DecodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Response) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4eaa2564DecodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV1(l, v)
}
func easyjson4eaa2564DecodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV11(in *jlexer.Lexer, out *Register) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "email":
			out.Email = string(in.String())
		case "password":
			out.Password = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "birthday":
			out.Birthday = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4eaa2564EncodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV11(out *jwriter.Writer, in Register) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix[1:])
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"birthday\":"
		out.RawString(prefix)
		out.String(string(in.Birthday))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Register) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4eaa2564EncodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Register) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4eaa2564EncodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Register) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4eaa2564DecodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Register) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4eaa2564DecodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV11(l, v)
}
func easyjson4eaa2564DecodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV12(in *jlexer.Lexer, out *Refresh) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "token":
			out.Token = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4eaa2564EncodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV12(out *jwriter.Writer, in Refresh) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"token\":"
		out.RawString(prefix[1:])
		out.String(string(in.Token))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Refresh) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4eaa2564EncodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Refresh) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4eaa2564EncodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Refresh) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4eaa2564DecodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Refresh) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4eaa2564DecodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV12(l, v)
}
func easyjson4eaa2564DecodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV13(in *jlexer.Lexer, out *Logout) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "token":
			out.Token = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4eaa2564EncodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV13(out *jwriter.Writer, in Logout) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"token\":"
		out.RawString(prefix[1:])
		out.String(string(in.Token))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Logout) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4eaa2564EncodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Logout) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4eaa2564EncodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Logout) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4eaa2564DecodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Logout) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4eaa2564DecodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV13(l, v)
}
func easyjson4eaa2564DecodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV14(in *jlexer.Lexer, out *Login) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "email":
			out.Email = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4eaa2564EncodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV14(out *jwriter.Writer, in Login) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix[1:])
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Login) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4eaa2564EncodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Login) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4eaa2564EncodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Login) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4eaa2564DecodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Login) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4eaa2564DecodeGithubComAlexBlackNnAuthloyaltyInternalHandlersapiV14(l, v)
}
